python iterate_simulation_minimize_coal.py 28
python iterate_simulation_minimize_coal.py 24
python iterate_simulation_minimize_coal.py 20
python iterate_simulation_minimize_coal.py 16
python iterate_simulation_minimize_coal.py 12
pause